"""The declarative base and the shared column conventions.

Two conventions here are worth stating because they are applied everywhere and
would be tedious to justify at each use.

Identifiers are UUIDs generated by the database. On one machine an integer
sequence would do, but citations and audit records are exported, quoted in bug
reports and compared across a re-import — and a sequence makes two unrelated
rows collide the moment anything is merged.

Timestamps are `timestamptz`, always. A naive timestamp on a laptop that
travels is a timestamp that lies twice a year, and the audit log's whole value
is that its ordering is trustworthy.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming, so a constraint is droppable by a name Alembic can predict
# rather than one Postgres invented. Autogenerated migrations are unreadable
# without this and, worse, are not reversible by name.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[uuid.UUID]:
    """A primary key the database generates."""
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at() -> Mapped[datetime]:
    """When the row was written, in UTC, according to the database."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
