"""Load an inferred CSV/spreadsheet table into its own sandbox database.
`M4-CSV-ING-094`.

`docs/data-sources.md` §2 and `askwell.table_infer`'s own docstring: parsing
and inference (`M4-CSV-ING-092`/`M4-CSV-ING-093`) never apply a guess
silently. This module is the next step — turning a reviewed inference into a
real, queryable table — and inherits the same rule: a column `table_infer`
could not resolve with confidence (`ColumnInference.ambiguous`, which
includes an undecided date format) is loaded as `text`, verbatim, rather than
coerced into the type Askwell merely suspects. Answering the clarification
that resolves it is what makes `reload_source` below re-load that one column
as the real type — the table is queryable from the first load, just narrower
than it will be once every question is answered.

**Isolation is `askwell.sandbox`, the same as a dump's (C3).** A CSV's own
content is never executed as SQL the way a dump's is — every value is cast in
Python and inserted through a parameterised statement, and every identifier
(table and column names) is generated by `askwell.sandbox`'s isolation-owning
code, never taken from the file — so there is no equivalent of "a hostile
CSV" at the level `M4-DUMP-SEC-091` tests for a dump. The sandbox is still
the right home for the data: it is one database per source, with no route to
Askwell's own database or the network, which is exactly the property a wrong
guess about someone's numbers should not be able to spread past.

**Row failures are reported, never dropped.** `docs/backlog`'s own validation
rule for this ticket. A value that cannot be cast to its column's type — an
`abc` in an integer column no inference flagged as ambiguous, because the
sample that decided the type did not happen to include it — is skipped, and
its 1-indexed row number (counting the header as row 1, the same convention
`table_infer.MalformedTable` uses) is collected onto `LoadResult.failed_rows`
rather than aborting the load or silently omitting the row with no trace.

**A CSV's owner role is unsealed and resealed around a reload, not sealed for
good.** `askwell.dump_import.import_dump` calls `sandbox.seal_owner` the
moment a dump succeeds because a dump is never touched again (`docs/backlog`:
"an import is a single attempt"). A table source is different: answering a
date-format clarification later needs a further owner-privileged write, so
`load_source` seals the same way a dump does when it finishes, and
`reload_source` brackets its own rebuild with `sandbox.unseal_owner` /
`sandbox.seal_owner` rather than leaving the grant open between reloads that
may be arbitrarily far apart.

**A reload rebuilds the whole table from the source file, not one column in
place.** The alternative — `ALTER TABLE ... ALTER COLUMN ... TYPE date USING
...` — aborts the entire statement on the first row that fails to parse,
which is exactly the all-or-nothing behaviour the row-level reporting rule
exists to avoid, and doing it column-by-column would need a stable per-row
join key this table has no other reason to carry. Re-parsing the file and
re-inserting every row is more I/O for a rare, user-initiated event, in
exchange for reusing the exact same per-row cast-and-report path the initial
load already uses — one implementation of "insert a row, catch what fails",
not two.
"""

import asyncio
import json
import os
import re
import time
import uuid
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

import psycopg
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from askwell import audit, paths, sandbox
from askwell.audit import Store
from askwell.config import Settings
from askwell.db.engine import session_scope
from askwell.filetypes import WORKBOOK_MIME
from askwell.logging import get_logger
from askwell.memory import write_schema_note
from askwell.table_infer import (
    ColumnInference,
    DateFormatVerdict,
    HeaderVerdict,
    TableInference,
    infer_csv,
    infer_xlsx,
    raise_table_inference,
    raise_workbook_questions,
)

log = get_logger(__name__)

TABLE_LOAD_STARTED = "table_load_started"
TABLE_LOAD_SUCCEEDED = "table_load_succeeded"
TABLE_LOAD_FAILED = "table_load_failed"
TABLE_COLUMN_RELOADED = "table_column_reloaded"

# Same booleans `table_infer._classify` recognises, duplicated rather than
# imported: this is the fixed vocabulary the *cast* step agrees with, and
# importing a name prefixed `_` across modules would read as a private
# implementation detail this module happens to reach into, when it is really
# a shared, stable convention both sides need to agree on independently.
_TRUE_VALUES = frozenset({"true", "t", "yes", "y", "1"})
_FALSE_VALUES = frozenset({"false", "f", "no", "n", "0"})

_NUMERIC_DATE = re.compile(r"^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})$")
_ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

_SQL_TYPE_BY_INFERRED_TYPE = {
    "integer": "bigint",
    "decimal": "numeric",
    "boolean": "boolean",
    "date": "date",
    "string": "text",
}

# Rows go in `BATCH_ROWS` at a time, all batches inside one transaction
# (`M11-FIX-ING-234`, #862): one autocommitted `INSERT` per row could not load
# 100,000 rows inside the default time cap. Both caps are checked after every
# batch, including the last, so a batch that crosses the size cap is caught
# the moment it lands. The size query costs a connection, which is why it runs
# per batch and not per row.
BATCH_ROWS = 1000


class TableLoadFailed(RuntimeError):
    """The table did not load. `str(exc)` is the reason — shown to the user
    and recorded as the sandbox database's drop reason, same shape as
    `dump_import.DumpImportFailed`."""


class TableCapExceeded(TableLoadFailed):
    """The load was aborted for crossing the size or time cap shared with a
    dump import (`docs/backlog` M4-CSV-ING-094's own edge case: "subject to
    the same size and time caps as a dump"). Deliberately the same caps,
    read through `askwell.dump_import`'s own settings, rather than a second
    pair of numbers a user would have to discover and set twice."""

    def __init__(self, cap: str, limit: float, message: str) -> None:
        super().__init__(message)
        self.cap = cap
        self.limit = limit


class EmptyTable(TableLoadFailed):
    """The file had nothing to load — `docs/backlog`'s own edge case: "An
    empty file — refused with the reason." Never reaches the sandbox at
    all: there is no database to create for a table with no columns."""


@dataclass(frozen=True, slots=True)
class RowFailure:
    row_number: int
    reason: str


@dataclass(frozen=True, slots=True)
class LoadResult:
    table_name: str
    sql_table_name: str
    row_count: int
    failed_rows: list[RowFailure] = field(default_factory=list)


def _format_bytes(count: float) -> str:
    value = float(count)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def _database_size(admin_url: str, database: str) -> int:
    with psycopg.connect(admin_url, autocommit=True) as admin:
        row = admin.execute("SELECT pg_database_size(%s)", (database,)).fetchone()
    assert row is not None
    return int(row[0])


# --- identifier normalisation -----------------------------------------------


def normalise_identifier(name: str, seen: set[str]) -> str:
    """A valid, unique Postgres identifier for one column or table name.

    `docs/backlog`'s own edge case: "A column name that is not a valid
    identifier — normalised, with the original recorded as a schema note so
    questions using the original name still work." `seen` makes two columns
    that normalise to the same thing (`"Amount"` and `"amount!"`) collide
    into `amount`/`amount_2` instead of one silently overwriting the other
    in the `CREATE TABLE` statement.
    """
    base = re.sub(r"[^a-z0-9_]+", "_", name.strip().lower()).strip("_") or "column"
    if base[0].isdigit():
        base = f"c_{base}"
    candidate = base
    suffix = 2
    while candidate in seen:
        candidate = f"{base}_{suffix}"
        suffix += 1
    seen.add(candidate)
    return candidate


def normalise_columns(names: list[str]) -> list[str]:
    """`normalise_identifier` applied in column order with one shared `seen`
    set — the same function `load_source` and `reload_source` both call, so
    a reload always agrees with the load it is correcting about which
    physical column a header name maps to."""
    seen: set[str] = set()
    return [normalise_identifier(name, seen) for name in names]


# --- typing and casting ------------------------------------------------------


def sql_type_for(
    column: ColumnInference, *, day_first_override: bool | None
) -> tuple[str, bool | None]:
    """The SQL type a column loads as, and the day-first/month-first
    decision a `date` column casts numeric values with — `None` when the
    column carries no such ambiguity (ISO, named-month, or not a date at
    all) or when the day-first/month-first question is not yet answered.

    An ambiguous column (`ColumnInference.ambiguous`) loads as `text`,
    verbatim, unless `day_first_override` — an answered `date_format`
    clarification's own DD/MM-vs-MM/DD verdict — resolves it. Every other
    ambiguity `table_infer` raises (a blank header, a mixed number format)
    has no discrete resolution to load against, so it stays `text` even
    after the clarification is answered; only the schema note describing it
    changes, via `askwell.reapply`.
    """
    if column.ambiguous:
        is_undecided_date = (
            column.date_format is not None
            and column.date_format.verdict is DateFormatVerdict.AMBIGUOUS
        )
        if is_undecided_date and day_first_override is not None:
            return "date", day_first_override
        return "text", None

    if column.inferred_type == "date":
        verdict = column.date_format.verdict if column.date_format is not None else None
        if verdict is DateFormatVerdict.DAY_FIRST:
            return "date", True
        if verdict is DateFormatVerdict.MONTH_FIRST:
            return "date", False
        # NOT_APPLICABLE: no numeric d/d/y value in the column at all (ISO or
        # named-month only), so no day-first/month-first decision is ever
        # consulted by `_cast_value`.
        return "date", None

    return _SQL_TYPE_BY_INFERRED_TYPE.get(column.inferred_type, "text"), None


def _parse_date(value: str, day_first: bool | None) -> Any:
    from datetime import date, datetime

    if _ISO_DATE.match(value):
        return date.fromisoformat(value)
    for fmt in ("%d %B %Y", "%d %b %Y"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            continue
    match = _NUMERIC_DATE.match(value)
    if not match:
        raise ValueError(f"{value!r} does not match a recognised date shape")
    if day_first is None:
        raise ValueError(f"{value!r} is a date whose day/month order was never decided")
    first, second, year_text = (int(part) for part in match.groups())
    year = year_text if year_text >= 100 else year_text + 2000
    day, month = (first, second) if day_first else (second, first)
    return date(year, month, day)


def cast_value(raw: str, sql_type: str, day_first: bool | None) -> Any:
    """One cell, cast to its column's SQL type — `None` for a blank cell in
    any column, never coerced to `0` or an empty string. Raises `ValueError`
    for a value that does not fit, caught per row by `_insert_rows_blocking` and
    turned into a `RowFailure` rather than aborting the load."""
    value = raw.strip()
    if not value:
        return None
    if sql_type == "bigint":
        return int(value)
    if sql_type == "numeric":
        try:
            return Decimal(value.replace(",", ""))
        except InvalidOperation as error:
            raise ValueError(f"{value!r} is not a number") from error
    if sql_type == "boolean":
        low = value.lower()
        if low in _TRUE_VALUES:
            return True
        if low in _FALSE_VALUES:
            return False
        raise ValueError(f"{value!r} is not a recognised boolean")
    if sql_type == "date":
        return _parse_date(value, day_first)
    return value


# --- creating and populating one table ---------------------------------------


def _create_table_blocking(
    dsn: str, sql_table_name: str, columns: list[tuple[str, str]], comment: str | None = None
) -> None:
    from psycopg import sql as psql

    column_defs = psql.SQL(", ").join(
        psql.SQL("{} {}").format(psql.Identifier(name), psql.SQL(sql_type))
        for name, sql_type in columns
    )
    with psycopg.connect(dsn, autocommit=True) as conn:
        conn.execute(psql.SQL("DROP TABLE IF EXISTS {}").format(psql.Identifier(sql_table_name)))
        conn.execute(
            psql.SQL("CREATE TABLE {} ({})").format(psql.Identifier(sql_table_name), column_defs)
        )
        if comment is not None:
            conn.execute(
                psql.SQL("COMMENT ON TABLE {} IS {}").format(
                    psql.Identifier(sql_table_name), psql.Literal(comment)
                )
            )


def _check_caps(
    admin_url: str,
    database: str,
    start: float,
    *,
    size_cap_bytes: int,
    time_cap_seconds: float,
) -> None:
    elapsed = time.monotonic() - start
    if elapsed > time_cap_seconds:
        raise TableCapExceeded(
            "time",
            time_cap_seconds,
            f"Load aborted: running for {elapsed:.1f}s, over the time cap of "
            f"{time_cap_seconds:.1f}s.",
        )
    try:
        loaded = _database_size(admin_url, database)
    except Exception:  # pragma: no cover - the database always exists here
        loaded = None
    if loaded is not None and loaded > size_cap_bytes:
        raise TableCapExceeded(
            "size",
            size_cap_bytes,
            f"Load aborted: loaded data reached {_format_bytes(loaded)}, over "
            f"the size cap of {_format_bytes(size_cap_bytes)}.",
        )


def _insert_rows_blocking(
    dsn: str,
    admin_url: str,
    database: str,
    sql_table_name: str,
    sql_column_names: list[str],
    sql_types: list[str],
    day_firsts: list[bool | None],
    rows: list[list[str]],
    *,
    header_present: bool,
    size_cap_bytes: int,
    time_cap_seconds: float,
) -> list[RowFailure]:
    """Insert every row, `BATCH_ROWS` at a time, in one transaction.

    Each batch is one `executemany` under its own savepoint. When Postgres
    refuses a row the whole batch rolls back to that savepoint and is tried
    again row by row, each under its own savepoint, so the refused row is
    reported by its number and the rest of the batch still loads — the same
    `RowFailure`s the one-insert-per-row loader reported. A value Python
    cannot cast never reaches the database at all. A cap crossed rolls the
    whole transaction back; the caller drops what was created either way.
    """
    from psycopg import sql as psql

    insert_stmt = psql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        psql.Identifier(sql_table_name),
        psql.SQL(", ").join(psql.Identifier(name) for name in sql_column_names),
        psql.SQL(", ").join(psql.Placeholder() * len(sql_column_names)),
    )
    first_row_number = 2 if header_present else 1

    failures: list[RowFailure] = []
    start = time.monotonic()
    with psycopg.connect(dsn) as conn, conn.transaction(), conn.cursor() as cursor:
        for batch_start in range(0, len(rows), BATCH_ROWS):
            batch_failures: list[RowFailure] = []
            castable: list[tuple[int, list[Any]]] = []
            for offset, row in enumerate(
                rows[batch_start : batch_start + BATCH_ROWS], start=batch_start
            ):
                try:
                    values = [
                        cast_value(row[index], sql_types[index], day_firsts[index])
                        if index < len(row)
                        else None
                        for index in range(len(sql_column_names))
                    ]
                except ValueError as error:
                    batch_failures.append(RowFailure(offset + first_row_number, str(error)))
                else:
                    castable.append((offset + first_row_number, values))

            try:
                if castable:
                    with conn.transaction():
                        cursor.executemany(insert_stmt, [values for _, values in castable])
            except psycopg.Error:
                if conn.broken:
                    raise
                for row_number, values in castable:
                    try:
                        with conn.transaction():
                            cursor.execute(insert_stmt, values)
                    except psycopg.Error as error:
                        if conn.broken:
                            raise
                        batch_failures.append(RowFailure(row_number, str(error)))

            failures.extend(sorted(batch_failures, key=lambda failure: failure.row_number))
            _check_caps(
                admin_url,
                database,
                start,
                size_cap_bytes=size_cap_bytes,
                time_cap_seconds=time_cap_seconds,
            )
    return failures


# --- registering and orchestrating one source --------------------------------


async def create_table_source(session: AsyncSession, name: str, file_path: str) -> uuid.UUID:
    """Register a table source ahead of parsing and loading it — the `csv`
    counterpart of `dump_import.create_dump_source`. `root_path` carries the
    file's own path, the same column and the same reasoning: it is not a
    folder Askwell indexes in place, but it is still where this source's
    material actually is.
    """
    result = await session.execute(
        text(
            "INSERT INTO sources (kind, name, root_path, status) "
            "VALUES ('csv', :name, :root_path, 'queued') RETURNING id"
        ),
        {"name": name, "root_path": file_path},
    )
    source_id = result.scalar_one()
    await audit.record(
        session,
        Store.DECISIONS,
        "source_added",
        {"source_id": str(source_id), "name": name, "kind": "csv"},
    )
    log.info("table_source_added", source_id=str(source_id), name=name)
    return uuid.UUID(str(source_id))


def _parse_file(host_path: Path) -> list[TableInference]:
    # Stored paths are host paths; reading one goes through the translation
    # (`askwell.paths`), which is the identity except on Windows.
    file_path = Path(paths.to_container(str(host_path)))
    raw = file_path.read_bytes()
    extension = file_path.suffix.lower().lstrip(".")
    if extension == "xlsx":
        return infer_xlsx(file_path.name, raw)
    return [infer_csv(file_path.name, raw)]


async def _date_format_overrides(
    session: AsyncSession, source_id: uuid.UUID
) -> dict[tuple[str, str], bool]:
    """Every answered `date_format` clarification for this source, as a
    `(table_name, column_name) -> day_first` map — the cumulative, durable
    record of every DD/MM-vs-MM/DD question answered so far, re-derived from
    `clarifications` itself rather than a second store: the clarification
    row already is the fact, and re-deriving it here is what lets
    `reload_source` rebuild correctly no matter how many separate answers
    led to this point.

    The subject is the bare column name and the table is in the evidence
    (#361). A row raised before that change has neither `table_name` in its
    evidence nor a bare subject, only `"{table}: {column}"`, and is still
    read that way.
    """
    rows = await session.execute(
        text(
            "SELECT subject, answer, options, evidence->>'table_name' FROM clarifications "
            "WHERE source_id = :source_id AND status = 'answered' "
            "AND evidence->>'trigger' = 'date_format'"
        ),
        {"source_id": source_id},
    )
    overrides: dict[tuple[str, str], bool] = {}
    for subject, answer, options, evidence_table_name in rows:
        if not answer:
            continue
        if evidence_table_name:
            table_name, column_name = evidence_table_name, subject
        elif ": " in subject:
            # The old format joined with `": "`. A sheet table's own colon
            # (`data.xlsx:North`) has no space after it; Excel forbids `:` in
            # a sheet name, so the first `": "` is always the join.
            table_name, column_name = (part.strip() for part in subject.split(": ", 1))
        else:
            continue
        day_first_option = (options or [None])[0]
        overrides[(table_name, column_name)] = answer == day_first_option
    return overrides


async def _load_table(
    dsn: str,
    admin_url: str,
    database: str,
    inference: TableInference,
    sql_table_name: str,
    *,
    overrides: dict[tuple[str, str], bool],
    size_cap_bytes: int,
    time_cap_seconds: float,
    comment: str | None = None,
) -> LoadResult:
    """Create one table and insert its rows, as the sandbox owner. Everything
    about a table that is not about the source it belongs to — the one path
    a CSV and a workbook's sheet (`M11-FIX-ING-224`) both load through."""
    sql_column_names = normalise_columns([column.name for column in inference.columns])

    sql_types: list[str] = []
    day_firsts: list[bool | None] = []
    for column in inference.columns:
        override = overrides.get((inference.table_name, column.name))
        sql_type, day_first = sql_type_for(column, day_first_override=override)
        sql_types.append(sql_type)
        day_firsts.append(day_first)

    await asyncio.to_thread(
        _create_table_blocking,
        dsn,
        sql_table_name,
        list(zip(sql_column_names, sql_types, strict=True)),
        comment,
    )
    failures = await asyncio.to_thread(
        _insert_rows_blocking,
        dsn,
        admin_url,
        database,
        sql_table_name,
        sql_column_names,
        sql_types,
        day_firsts,
        inference.rows,
        header_present=inference.header.verdict is HeaderVerdict.PRESENT,
        size_cap_bytes=size_cap_bytes,
        time_cap_seconds=time_cap_seconds,
    )
    return LoadResult(
        table_name=inference.table_name,
        sql_table_name=sql_table_name,
        row_count=len(inference.rows) - len(failures),
        failed_rows=failures,
    )


def _loaded_as(sql_table_name: str) -> str:
    """How a sheet's table-level note begins. `sheet_of_table` reads it back:
    it is the one record of which sheet a physical table holds."""
    return f"Loaded as table `{sql_table_name}`,"


async def _write_load_notes(
    session: AsyncSession,
    source_id: uuid.UUID,
    inferences: list[TableInference],
    results: list[LoadResult],
) -> None:
    """The table-level note naming the physical table, and one note per
    column whose header had to be renamed to become an identifier."""
    for inference, result in zip(inferences, results, strict=True):
        await write_schema_note(
            session,
            source_id=source_id,
            table_name=inference.table_name,
            column_name=None,
            description=(
                f"{_loaded_as(result.sql_table_name)} "
                f"{result.row_count} row(s), {len(inference.columns)} column(s)."
                + (
                    f" {len(result.failed_rows)} row(s) failed to load."
                    if result.failed_rows
                    else ""
                )
            ),
            origin="inferred",
            confidence=1.0,
        )
        sql_names = normalise_columns([c.name for c in inference.columns])
        for sql_name, column in zip(sql_names, inference.columns, strict=True):
            if sql_name != column.name:
                await write_schema_note(
                    session,
                    source_id=source_id,
                    table_name=inference.table_name,
                    column_name=column.name,
                    description=(
                        f"Loaded as column `{sql_name}` — the original header "
                        f"was {column.name!r}, which is not a valid column name."
                    ),
                    origin="inferred",
                    confidence=1.0,
                )


async def _load_inferences(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    inferences: list[TableInference],
    *,
    overrides: dict[tuple[str, str], bool],
    is_reload: bool,
) -> list[LoadResult]:
    from askwell.dump_import import get_dump_size_cap_bytes, get_dump_time_cap_seconds

    non_empty = [inference for inference in inferences if inference.columns]
    if not non_empty:
        raise EmptyTable("the file has no rows or columns to load")

    admin_url = settings.sandbox_database_url.get_secret_value()
    owner_password = settings.sandbox_owner_password.get_secret_value()

    async with session_scope(factory) as session:
        size_cap_bytes = await get_dump_size_cap_bytes(session)
        time_cap_seconds = await get_dump_time_cap_seconds(session)
        row = (
            await session.execute(
                text("SELECT sandbox_db FROM sources WHERE id = :id"), {"id": source_id}
            )
        ).first()
        assert row is not None, "load_source called against a source that does not exist"
        database = row[0]
        if database is None:
            database = sandbox.generate_name()
            await sandbox.create_database(session, admin_url, database)
            await session.execute(
                text("UPDATE sources SET sandbox_db = :db, status = 'indexing' WHERE id = :id"),
                {"db": database, "id": source_id},
            )
        elif is_reload:
            await sandbox.unseal_owner(session, admin_url, database)
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_LOAD_STARTED,
            {"source_id": str(source_id), "database": database, "reload": is_reload},
        )

    dsn = sandbox.owner_url(admin_url, database, owner_password)
    results: list[LoadResult] = []
    # Shared across every sheet in this source, not reset per inference — two
    # sheets whose names normalise the same way (`"Data"` and `"DATA!"`) must
    # not both claim the identifier `data`, the same collision
    # `normalise_columns` already guards against within one table's columns.
    sql_table_names: set[str] = set()

    try:
        for inference in non_empty:
            results.append(
                await _load_table(
                    dsn,
                    admin_url,
                    database,
                    inference,
                    normalise_identifier(inference.table_name, sql_table_names),
                    overrides=overrides,
                    size_cap_bytes=size_cap_bytes,
                    time_cap_seconds=time_cap_seconds,
                )
            )
    except Exception as error:
        reason = (
            str(error) if isinstance(error, TableLoadFailed) else f"{type(error).__name__}: {error}"
        )
        payload: dict[str, object] = {
            "source_id": str(source_id),
            "database": database,
            "reason": reason,
        }
        if isinstance(error, TableCapExceeded):
            payload["cap"] = error.cap
        async with session_scope(factory) as session:
            if not is_reload:
                await sandbox.drop_database(session, admin_url, database, reason=reason)
                await session.execute(
                    text(
                        "UPDATE sources SET sandbox_db = NULL, status = 'attention', "
                        "last_error = :error WHERE id = :id"
                    ),
                    {"error": reason, "id": source_id},
                )
            else:
                await session.execute(
                    text(
                        "UPDATE sources SET status = 'attention', last_error = :error "
                        "WHERE id = :id"
                    ),
                    {"error": reason, "id": source_id},
                )
            await audit.record(session, Store.DECISIONS, TABLE_LOAD_FAILED, payload)
        log.warning("table_load_failed", source_id=str(source_id), database=database, reason=reason)
        if isinstance(error, TableLoadFailed):
            raise
        raise TableLoadFailed(reason) from error

    async with session_scope(factory) as session:
        await sandbox.seal_owner(session, admin_url, database)
        if not is_reload:
            # Written once, at the load that first creates the table —
            # `write_schema_note`'s own supersession rule only retires a
            # prior note for a `user`-origin write, so calling this again on
            # every reload would accumulate a duplicate `inferred` note per
            # reload rather than replacing the one already there. A reload
            # changes row counts, not the table's existence or its column
            # names, so nothing here goes stale across one.
            await _write_load_notes(session, source_id, non_empty, results)
        await session.execute(
            text("UPDATE sources SET status = 'ready', last_indexed_at = now() WHERE id = :id"),
            {"id": source_id},
        )
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_LOAD_SUCCEEDED,
            {
                "source_id": str(source_id),
                "database": database,
                "tables": [result.sql_table_name for result in results],
                "rows": sum(result.row_count for result in results),
                "failed_rows": sum(len(result.failed_rows) for result in results),
            },
        )
    log.info(
        "table_load_succeeded",
        source_id=str(source_id),
        database=database,
        tables=len(results),
        failed_rows=sum(len(result.failed_rows) for result in results),
    )
    return results


async def process_table_source(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    file_path: str,
) -> list[LoadResult]:
    """Parse, raise clarifications, and load — the one entry point a worker
    job calls end to end for a newly added CSV or spreadsheet source.

    Parsing and clarification-raising (`M4-CSV-ING-092`/`093`,
    `askwell.table_infer`) run first and unconditionally: every column lands
    in `schema_notes` and every unresolved one becomes a real clarification
    regardless of what the load itself does, the same as before this ticket
    existed. Loading (this ticket) always follows in the same run — a column
    still ambiguous when it does simply loads as `text`, per `sql_type_for`.
    """
    inferences = _parse_file(Path(file_path))

    async with session_scope(factory) as session:
        for inference in inferences:
            await raise_table_inference(session, source_id, inference)

    return await _load_inferences(
        factory, settings, source_id, inferences, overrides={}, is_reload=False
    )


async def load_source(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    file_path: str,
) -> list[LoadResult]:
    """Load already-inferred, already-raised tables — split out from
    `process_table_source` so a test (or a future retry path) can load
    without re-raising clarifications a source already has."""
    inferences = _parse_file(Path(file_path))
    return await _load_inferences(
        factory, settings, source_id, inferences, overrides={}, is_reload=False
    )


async def reload_source(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    table_name: str | None = None,
) -> list[LoadResult] | None:
    """Re-load every table this source produced, applying every
    `date_format` clarification answered so far. `askwell.reapply` calls
    this once a date-format clarification's own answer is recorded, so a
    column loaded as `text` because its day/month order was undecided
    becomes a real `date` the moment that is settled.

    A folder (`M11-FIX-ING-228`) reloads only the workbook whose sheet
    `table_name` names, through `load_workbook_tables`, which finds that
    workbook's tables by their comment and leaves every other workbook's
    alone. The reload runs in the folder's own sandbox database (C3).

    Returns `None` without touching the sandbox when the source is neither a
    `csv` source nor a folder with that workbook in it, or has not loaded
    yet — `askwell.reapply`'s dependency resolution matches on
    `schema_notes` alone and cannot tell a table source's inferred note from
    any other source's, so this is the one place that actually checks.
    """
    async with session_scope(factory) as session:
        row = (
            await session.execute(
                text("SELECT kind, root_path, sandbox_db FROM sources WHERE id = :id"),
                {"id": source_id},
            )
        ).first()
        if row is not None and row[0] == "file" and row[2] is not None and table_name:
            document = await _workbook_of_table(session, source_id, table_name)
        else:
            document = None
    if document is not None:
        document_id, relative = document
        outcome = await load_workbook_tables(factory, settings, source_id, document_id)
        async with session_scope(factory) as session:
            # No document is indexing here, so nothing else will refresh the
            # folder: a reload that failed, or that cleared an earlier
            # failure, moves its attention now (`M11-FIX-UI-229`).
            from askwell import ingest

            await ingest.refresh_source(
                session, source_id, settings.ocr_confidence_threshold, settings
            )
            await audit.record(
                session,
                Store.DECISIONS,
                TABLE_COLUMN_RELOADED,
                {
                    "source_id": str(source_id),
                    "workbook": relative,
                    "tables": [result.sql_table_name for result in outcome.tables],
                    "failed_rows": sum(len(result.failed_rows) for result in outcome.tables),
                },
            )
        return outcome.tables

    if row is None or row[0] != "csv" or row[2] is None:
        return None
    async with session_scope(factory) as session:
        overrides = await _date_format_overrides(session, source_id)

    inferences = _parse_file(Path(row[1]))
    results = await _load_inferences(
        factory, settings, source_id, inferences, overrides=overrides, is_reload=True
    )
    async with session_scope(factory) as session:
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_COLUMN_RELOADED,
            {
                "source_id": str(source_id),
                "tables": [result.sql_table_name for result in results],
                "failed_rows": sum(len(result.failed_rows) for result in results),
            },
        )
    return results


# --- a workbook's sheets, alongside its document (`M11-FIX-ING-224`) ----------

WORKBOOK_TABLES_LOADED = "workbook_tables_loaded"
WORKBOOK_TABLES_FAILED = "workbook_tables_failed"

# Every table a workbook's sheets become carries this comment, followed by the
# workbook's path inside its folder. The comment, not the table name, is how a
# reload finds its own tables: two workbooks whose names normalise the same
# way (`a b.xlsx`, `a_b.xlsx`) get `a_b_xlsx_data` and `a_b_xlsx_data_2`, and
# only the comment says which is whose.
_WORKBOOK_COMMENT_PREFIX = "askwell workbook: "


def workbook_table_prefix(relative_path: str) -> str:
    """What every schema note for this workbook's sheets starts its
    `table_name` with — `infer_xlsx` names a sheet `<workbook>:<sheet>`."""
    return f"{relative_path}:"


def workbook_comment(relative_path: str) -> str:
    return f"{_WORKBOOK_COMMENT_PREFIX}{relative_path}"


def sheet_skip_reason(inference: TableInference) -> str | None:
    """Why a sheet does not become a table, or `None` when it does.

    A table needs column names, and a sheet's only source of them is its
    first row. When `detect_header` cannot say that row is names — it reads
    as data, or every column is free text and gives no signal — loading it
    would either name the columns `Column 1`, `Column 2`, which no question
    will ever use, or trust a guess `docs/data-sources.md` §2 says to ask
    about. A merged header cell cannot be split into per-column names at
    all. Such a sheet is still in the document's passages; it is only not a
    table.
    """
    if not inference.columns:
        return "the sheet is empty"
    if inference.merged_header:
        return "the header row has merged cells"
    if inference.header.verdict is not HeaderVerdict.PRESENT:
        return f"no recognisable header row: {inference.header.reason}"
    return None


@dataclass(frozen=True, slots=True)
class WorkbookOutcome:
    """What loading one workbook's sheets did. `skipped` is `(sheet, reason)`;
    `failure` is set when nothing was loaded because the load itself failed."""

    tables: list[LoadResult]
    skipped: list[tuple[str, str]]
    failure: str | None = None


def _relative_path(path: str, root: str | None) -> str:
    # Compared in container spelling so a Windows path's `\\` separators are
    # separators here too. The result only names a table.
    path = paths.to_container(path)
    root = paths.to_container(root) if root else root
    if root and os.path.commonpath([root, path]) == os.path.normpath(root) and path != root:
        return os.path.relpath(path, root).replace(os.sep, "/")
    return os.path.basename(path)


def _tables_blocking(dsn: str) -> dict[str, str | None]:
    """Every table in a sandbox database, with its comment."""
    with psycopg.connect(dsn, autocommit=True) as conn:
        rows = conn.execute(
            "SELECT c.relname, obj_description(c.oid, 'pg_class') FROM pg_class c "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = 'public' AND c.relkind = 'r'"
        ).fetchall()
    return {str(name): comment for name, comment in rows}


def _orphaned(tables: dict[str, str | None], live: set[str]) -> list[str]:
    """The workbook tables whose workbook is no longer a live document."""
    return sorted(
        name
        for name, comment in tables.items()
        if comment is not None
        and comment.startswith(_WORKBOOK_COMMENT_PREFIX)
        and comment[len(_WORKBOOK_COMMENT_PREFIX) :] not in live
    )


async def _workbook_of_table(
    session: AsyncSession, source_id: uuid.UUID, table_name: str
) -> tuple[uuid.UUID, str] | None:
    """The live workbook whose sheet `table_name` (`<path>:<sheet>`) is, as
    its newest document and its path inside the folder."""
    rows = await session.execute(
        text(
            "SELECT d.id, d.path, s.root_path FROM documents d "
            "JOIN sources s ON s.id = d.source_id "
            "WHERE d.source_id = :id AND d.mime = :mime AND d.deleted_at IS NULL "
            "AND d.superseded_by IS NULL ORDER BY d.added_at DESC"
        ),
        {"id": source_id, "mime": WORKBOOK_MIME},
    )
    for document_id, path, root in rows:
        relative = _relative_path(str(path), root)
        if table_name.startswith(workbook_table_prefix(relative)):
            return uuid.UUID(str(document_id)), relative
    return None


async def workbook_tables(settings: Settings, database: str) -> dict[str, str]:
    """Every workbook sheet table in a folder's sandbox database, with the
    workbook's path inside the folder its comment names. Read as the
    read-only role: this is for answering, not loading."""
    admin_url = settings.sandbox_database_url.get_secret_value()
    password = settings.sandbox_readonly_password.get_secret_value()
    tables = await asyncio.to_thread(
        _tables_blocking, sandbox.readonly_url(admin_url, database, password)
    )
    return {
        name: comment[len(_WORKBOOK_COMMENT_PREFIX) :]
        for name, comment in tables.items()
        if comment is not None and comment.startswith(_WORKBOOK_COMMENT_PREFIX)
    }


async def sheet_of_table(
    session: AsyncSession, source_id: uuid.UUID, relative_path: str, sql_table_name: str
) -> str | None:
    """The sheet of `relative_path` loaded as `sql_table_name`, from the
    table-level note `_write_load_notes` wrote for it. `None` when that note
    is gone, which a person's own note on the table replaces."""
    prefix = workbook_table_prefix(relative_path)
    rows = await session.execute(
        text(
            "SELECT table_name, description FROM schema_notes "
            "WHERE source_id = :id AND column_name IS NULL AND origin = 'inferred' "
            "AND superseded_by IS NULL AND left(table_name, length(:prefix)) = :prefix"
        ),
        {"id": source_id, "prefix": prefix},
    )
    for table_name, description in rows:
        if str(description).startswith(_loaded_as(sql_table_name)):
            return str(table_name)[len(prefix) :]
    return None


async def live_workbook(
    session: AsyncSession, source_id: uuid.UUID, relative_path: str
) -> uuid.UUID | None:
    """The live, newest document of the workbook at `relative_path`."""
    found = await _workbook_of_table(session, source_id, workbook_table_prefix(relative_path))
    if found is None or found[1] != relative_path:
        return None
    return found[0]


async def _live_workbooks(session: AsyncSession, source_id: uuid.UUID) -> set[str]:
    rows = await session.execute(
        text(
            "SELECT d.path, s.root_path FROM documents d JOIN sources s ON s.id = d.source_id "
            "WHERE d.source_id = :id AND d.mime = :mime AND d.deleted_at IS NULL"
        ),
        {"id": source_id, "mime": WORKBOOK_MIME},
    )
    return {_relative_path(str(path), root) for path, root in rows}


def _drop_tables_blocking(dsn: str, names: list[str]) -> None:
    from psycopg import sql as psql

    with psycopg.connect(dsn, autocommit=True) as conn:
        for name in names:
            conn.execute(psql.SQL("DROP TABLE IF EXISTS {}").format(psql.Identifier(name)))


async def _forget_workbook_notes(session: AsyncSession, source_id: uuid.UUID, prefix: str) -> None:
    """Retire what Askwell inferred about this workbook's sheets. A note a
    person wrote is left alone, the same rule `write_schema_inventory`
    follows: nothing here deletes what someone said."""
    await session.execute(
        text(
            "DELETE FROM schema_notes WHERE source_id = :id AND origin = 'inferred' "
            "AND left(table_name, length(:prefix)) = :prefix"
        ),
        {"id": source_id, "prefix": prefix},
    )


async def load_workbook_tables(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    document_id: uuid.UUID,
) -> WorkbookOutcome:
    """Load each sheet of an indexed workbook as a table, alongside its
    document. `M11-FIX-ING-224`, issue #827.

    The tables go into the folder source's own sandbox database (C3), created
    on the first workbook and shared by every workbook in that folder, so a
    workbook stays one source in the library. Each sheet goes through the
    same `_load_table` a CSV does, under the same size and time caps, and its
    notes are written the way a CSV's are. Two things differ, both because
    the source is a folder rather than a table:

    - the source's status is not set here. The outcome is kept on the
      document (`_store_outcome`, `M11-FIX-UI-229`), and the source's next
      `ingest.refresh_source` reads it: a failed load is `attention`, naming
      the workbook, sheet and reason; a skipped sheet is only a note, since
      nothing failed. The document itself is never failed by either;
    - its questions are asked once per workbook, within the folder's cap
      (`table_infer.raise_workbook_questions`, `M11-FIX-ING-228`). An
      ambiguous column loads as `text` until its question is answered, and
      as the answered type from then on, including when the workbook is
      indexed again.

    Never raises. A workbook's passages answer questions whether or not its
    tables exist, so the outcome is recorded — `workbook_tables_loaded` or
    `workbook_tables_failed`, with the source id — and returned, and the
    document is indexed either way.
    """
    try:
        return await _load_workbook_tables(factory, settings, source_id, document_id)
    except Exception as error:
        reason = f"{type(error).__name__}: {error}"
        log.exception("workbook_tables_failed", source_id=str(source_id), reason=reason)
        try:
            async with session_scope(factory) as session:
                await _store_outcome(session, document_id, (None, reason), [])
                await audit.record(
                    session,
                    Store.DECISIONS,
                    WORKBOOK_TABLES_FAILED,
                    {
                        "source_id": str(source_id),
                        "document_id": str(document_id),
                        "reason": reason,
                    },
                )
        except Exception:
            log.exception("workbook_tables_failure_unrecorded", source_id=str(source_id))
        return WorkbookOutcome(tables=[], skipped=[], failure=reason)


async def _load_workbook_tables(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    document_id: uuid.UUID,
) -> WorkbookOutcome:
    from askwell.dump_import import get_dump_size_cap_bytes, get_dump_time_cap_seconds

    async with session_scope(factory) as session:
        row = (
            await session.execute(
                text(
                    "SELECT d.path, s.root_path FROM documents d "
                    "JOIN sources s ON s.id = d.source_id "
                    "WHERE d.id = :document_id AND d.source_id = :source_id "
                    "AND d.deleted_at IS NULL AND s.status != 'deleted'"
                ),
                {"document_id": document_id, "source_id": source_id},
            )
        ).first()
    if row is None:
        # Deleted while its document was indexing: nothing to load for.
        return WorkbookOutcome(tables=[], skipped=[])
    path, root = str(row[0]), row[1]
    relative = _relative_path(path, root)
    prefix, comment = workbook_table_prefix(relative), workbook_comment(relative)

    raw = await asyncio.to_thread(Path(paths.to_container(path)).read_bytes)
    inferences = await asyncio.to_thread(infer_xlsx, relative, raw)
    loadable: list[TableInference] = []
    skipped: list[tuple[str, str]] = []
    for inference in inferences:
        reason = sheet_skip_reason(inference)
        if reason is None:
            loadable.append(inference)
        else:
            skipped.append((inference.sheet or inference.table_name, reason))
            log.info(
                "workbook_sheet_skipped",
                source_id=str(source_id),
                workbook=relative,
                sheet=inference.sheet,
                reason=reason,
            )

    admin_url = settings.sandbox_database_url.get_secret_value()
    owner_password = settings.sandbox_owner_password.get_secret_value()

    # One workbook load per folder at a time. Two workbooks from one folder
    # are ingested concurrently (`ingest_concurrency`), and they share one
    # database: without this, both could create it, or one could reseal the
    # owner while the other is still inserting.
    async with session_scope(factory) as lock:
        await lock.execute(
            text("SELECT pg_advisory_xact_lock(hashtext('workbook_tables'), hashtext(:id))"),
            {"id": str(source_id)},
        )
        async with session_scope(factory) as session:
            size_cap_bytes = await get_dump_size_cap_bytes(session)
            time_cap_seconds = await get_dump_time_cap_seconds(session)
            overrides = await _date_format_overrides(session, source_id)
            database = (
                await session.execute(
                    text("SELECT sandbox_db FROM sources WHERE id = :id"), {"id": source_id}
                )
            ).scalar_one()
            created = database is None
            if created and not loadable:
                # Nothing loaded before and nothing to load now: no database.
                await _forget_workbook_notes(session, source_id, prefix)
                await _store_outcome(session, document_id, None, skipped)
                await _record_loaded(session, source_id, document_id, relative, [], skipped)
                return WorkbookOutcome(tables=[], skipped=skipped)
            if created:
                database = sandbox.generate_name()
                await sandbox.create_database(session, admin_url, database)
                await session.execute(
                    text("UPDATE sources SET sandbox_db = :db WHERE id = :id"),
                    {"db": database, "id": source_id},
                )
            else:
                await sandbox.unseal_owner(session, admin_url, database)

            live = await _live_workbooks(session, source_id)

        dsn = sandbox.owner_url(admin_url, database, owner_password)
        own: list[str] = []
        results: list[LoadResult] = []
        # The sheet being loaded when something failed, so the library can
        # name it. `None` while dropping the previous tables, which no one
        # sheet is responsible for.
        current: str | None = None
        try:
            existing = await asyncio.to_thread(_tables_blocking, dsn)
            own = [name for name, note in existing.items() if note == comment]
            # This workbook's previous tables, and any a deleted workbook left
            # behind (#852) — see `sweep_workbook_tables`.
            replaced = sorted(set(own) | set(_orphaned(existing, live)))
            await asyncio.to_thread(_drop_tables_blocking, dsn, replaced)
            taken = set(existing) - set(replaced)
            for inference in loadable:
                current = inference.sheet or inference.table_name
                sql_table_name = normalise_identifier(inference.table_name, taken)
                own.append(sql_table_name)
                results.append(
                    await _load_table(
                        dsn,
                        admin_url,
                        database,
                        inference,
                        sql_table_name,
                        overrides=overrides,
                        size_cap_bytes=size_cap_bytes,
                        time_cap_seconds=time_cap_seconds,
                        comment=comment,
                    )
                )
        except Exception as error:
            reason = (
                str(error)
                if isinstance(error, TableLoadFailed)
                else f"{type(error).__name__}: {error}"
            )
            payload: dict[str, object] = {
                "source_id": str(source_id),
                "document_id": str(document_id),
                "workbook": relative,
                "database": database,
                "reason": reason,
            }
            if isinstance(error, TableCapExceeded):
                payload["cap"] = error.cap
            async with session_scope(factory) as session:
                # Nothing half-loaded is left to answer from.
                if created:
                    await sandbox.drop_database(session, admin_url, database, reason=reason)
                    await session.execute(
                        text("UPDATE sources SET sandbox_db = NULL WHERE id = :id"),
                        {"id": source_id},
                    )
                else:
                    await asyncio.to_thread(_drop_tables_blocking, dsn, own)
                    await sandbox.seal_owner(session, admin_url, database)
                await _forget_workbook_notes(session, source_id, prefix)
                await _store_outcome(session, document_id, (current, reason), skipped)
                await audit.record(session, Store.DECISIONS, WORKBOOK_TABLES_FAILED, payload)
            log.warning(
                "workbook_tables_failed",
                source_id=str(source_id),
                workbook=relative,
                reason=reason,
            )
            return WorkbookOutcome(tables=[], skipped=skipped, failure=reason)

        async with session_scope(factory) as session:
            await sandbox.seal_owner(session, admin_url, database)
            await _forget_workbook_notes(session, source_id, prefix)
            for inference in loadable:
                await raise_table_inference(
                    session, source_id, inference, raise_clarifications=False
                )
            await raise_workbook_questions(session, source_id, relative, loadable)
            await _write_load_notes(session, source_id, loadable, results)
            await _store_outcome(session, document_id, None, skipped)
            await _record_loaded(session, source_id, document_id, relative, results, skipped)

    log.info(
        "workbook_tables_loaded",
        source_id=str(source_id),
        workbook=relative,
        tables=len(results),
        skipped=len(skipped),
    )
    return WorkbookOutcome(tables=results, skipped=skipped)


async def _store_outcome(
    session: AsyncSession,
    document_id: uuid.UUID,
    failure: tuple[str | None, str] | None,
    skipped: list[tuple[str, str]],
) -> None:
    """Keep what this load did on the workbook's document, where the library
    reads it (`M11-FIX-UI-229`, #849) — the decisions store records the same
    thing, but nothing on screen reads that. Both columns are overwritten on
    every load, so a workbook indexed again successfully loses its note."""
    await session.execute(
        text(
            "UPDATE documents SET sheet_load_failure = CAST(:failure AS jsonb), "
            "sheets_skipped = CAST(:skipped AS jsonb) WHERE id = :id"
        ),
        {
            "id": document_id,
            "failure": (
                None if failure is None else json.dumps({"sheet": failure[0], "reason": failure[1]})
            ),
            "skipped": (
                json.dumps([{"sheet": sheet, "reason": reason} for sheet, reason in skipped])
                if skipped
                else None
            ),
        },
    )


async def _record_loaded(
    session: AsyncSession,
    source_id: uuid.UUID,
    document_id: uuid.UUID,
    workbook: str,
    results: list[LoadResult],
    skipped: list[tuple[str, str]],
) -> None:
    await audit.record(
        session,
        Store.DECISIONS,
        WORKBOOK_TABLES_LOADED,
        {
            "source_id": str(source_id),
            "document_id": str(document_id),
            "workbook": workbook,
            "tables": [result.sql_table_name for result in results],
            "rows": sum(result.row_count for result in results),
            "failed_rows": sum(len(result.failed_rows) for result in results),
            "skipped": [{"sheet": sheet, "reason": reason} for sheet, reason in skipped],
        },
    )


# --- a deleted workbook's tables (#852) ----------------------------------------

WORKBOOK_TABLES_DROPPED = "workbook_tables_dropped"


async def forget_deleted_workbook(session: AsyncSession, document_id: uuid.UUID) -> None:
    """Make a deleted workbook's sheet tables unreachable, in the caller's
    transaction — the one that tombstones the document.

    SQL generation and `match_tables` see a table only through its schema
    notes, so retiring the inferred ones takes the tables out of every
    answer the moment the delete commits. A note a person wrote is kept and
    marked stale, as `write_schema_inventory` does for a dropped table. The
    tables themselves are dropped later by `sweep_workbook_tables`: the
    sandbox is a separate instance, and a delete must not depend on it
    being up.

    Nothing happens when another live document in the folder has the same
    path — a newer version of the same file, whose tables these now are.
    """
    row = (
        await session.execute(
            text(
                "SELECT d.path, d.mime, d.source_id, s.root_path FROM documents d "
                "JOIN sources s ON s.id = d.source_id WHERE d.id = :id"
            ),
            {"id": document_id},
        )
    ).first()
    if row is None or row[1] != WORKBOOK_MIME:
        return
    relative = _relative_path(str(row[0]), row[3])
    source_id = row[2]
    if relative in await _live_workbooks(session, source_id):
        return
    prefix = workbook_table_prefix(relative)
    await _forget_workbook_notes(session, source_id, prefix)
    await session.execute(
        text(
            "UPDATE schema_notes SET stale = true, stale_reason = 'dropped' "
            "WHERE source_id = :id AND superseded_by IS NULL "
            "AND left(table_name, length(:prefix)) = :prefix"
        ),
        {"id": source_id, "prefix": prefix},
    )


async def sweep_workbook_tables(
    factory: async_sessionmaker[AsyncSession], settings: Settings
) -> int:
    """Drop every sheet table whose workbook is no longer a live document.
    Called at worker start, next to `sandbox.reclaim_orphans`; a load of any
    workbook in the same folder does the same for that folder. Returns how
    many tables were dropped."""
    admin_url = settings.sandbox_database_url.get_secret_value()
    owner_password = settings.sandbox_owner_password.get_secret_value()
    readonly_password = settings.sandbox_readonly_password.get_secret_value()
    async with session_scope(factory) as session:
        sources = (
            await session.execute(
                text(
                    "SELECT id, sandbox_db FROM sources WHERE kind = 'file' "
                    "AND sandbox_db IS NOT NULL AND status != 'deleted'"
                )
            )
        ).all()

    dropped = 0
    for source_id, database in sources:
        async with session_scope(factory) as lock:
            await lock.execute(
                text("SELECT pg_advisory_xact_lock(hashtext('workbook_tables'), hashtext(:id))"),
                {"id": str(source_id)},
            )
            async with session_scope(factory) as session:
                live = await _live_workbooks(session, source_id)
            # Read as the readonly role first, so a folder with nothing to
            # drop never reopens the owner's grant.
            tables = await asyncio.to_thread(
                _tables_blocking, sandbox.readonly_url(admin_url, database, readonly_password)
            )
            orphans = _orphaned(tables, live)
            if not orphans:
                continue
            async with session_scope(factory) as session:
                await sandbox.unseal_owner(session, admin_url, database)
            try:
                await asyncio.to_thread(
                    _drop_tables_blocking,
                    sandbox.owner_url(admin_url, database, owner_password),
                    orphans,
                )
            finally:
                async with session_scope(factory) as session:
                    await sandbox.seal_owner(session, admin_url, database)
            async with session_scope(factory) as session:
                await audit.record(
                    session,
                    Store.DECISIONS,
                    WORKBOOK_TABLES_DROPPED,
                    {"source_id": str(source_id), "database": database, "tables": orphans},
                )
            log.info("workbook_tables_dropped", source_id=str(source_id), tables=orphans)
            dropped += len(orphans)
    return dropped


# --- workbooks indexed before their sheets became tables (#850, #895) ---------

SANDBOX_DATABASE_LOST = "sandbox_database_lost"


async def forget_lost_databases(
    factory: async_sessionmaker[AsyncSession], settings: Settings
) -> list[uuid.UUID]:
    """Let go of every folder's sandbox database that no longer exists.
    `M11-FIX-ING-230`, issue #895. Called at worker start, before
    `sweep_workbook_tables`, which would otherwise fail connecting to it.

    Losing the sandbox volume while keeping the main one leaves a folder
    whose `sandbox_db` names nothing, and whose workbooks are all marked
    loaded. Its inferred notes describe tables that are not there, so they
    are retired, and `sandbox_db` is cleared so the next load creates a new
    database. The `sandbox_database_lost` decision is what makes the folder's
    workbooks eligible for `backfill_workbook_tables` again: a load decision
    older than it no longer counts. Recorded in the same transaction as the
    clear, so a stop between the two cannot strand a workbook.

    A `dump` or `csv` source whose database is gone is not handled here —
    its tables cannot be rebuilt from anything Askwell holds (#895).
    """
    admin_url = settings.sandbox_database_url.get_secret_value()
    known = set(await asyncio.to_thread(sandbox.known_databases, admin_url))
    async with session_scope(factory) as session:
        sources = (
            await session.execute(
                text(
                    "SELECT id, sandbox_db FROM sources WHERE kind = 'file' "
                    "AND sandbox_db IS NOT NULL AND status != 'deleted'"
                )
            )
        ).all()

    lost: list[uuid.UUID] = []
    for source_id, database in sources:
        if database in known:
            continue
        async with session_scope(factory) as session:
            await session.execute(
                text("SELECT pg_advisory_xact_lock(hashtext('workbook_tables'), hashtext(:id))"),
                {"id": str(source_id)},
            )
            cleared = await session.execute(
                text(
                    "UPDATE sources SET sandbox_db = NULL WHERE id = :id AND sandbox_db = :db "
                    "RETURNING id"
                ),
                {"id": source_id, "db": database},
            )
            if cleared.first() is None:
                continue
            # Every table a folder has is a workbook's sheet.
            await _forget_workbook_notes(session, source_id, "")
            await audit.record(
                session,
                Store.DECISIONS,
                SANDBOX_DATABASE_LOST,
                {"source_id": str(source_id), "database": database},
            )
        log.warning("sandbox_database_lost", source_id=str(source_id), database=database)
        lost.append(uuid.UUID(str(source_id)))
    return lost


async def _workbooks_without_tables(session: AsyncSession) -> list[tuple[uuid.UUID, uuid.UUID]]:
    """`(source_id, document_id)` for every live, `ready` workbook with no
    load decision since its folder last lost its database.

    Either decision counts. A workbook whose sheets were all skipped is
    recorded `workbook_tables_loaded` with no tables, so it is not rescanned
    at every start; one that failed is recorded `workbook_tables_failed`, and
    is retried by indexing it again, as any failed load is.
    """
    rows = await session.execute(
        text(
            "SELECT d.source_id, d.id FROM documents d JOIN sources s ON s.id = d.source_id "
            "WHERE d.mime = :mime AND d.status = 'ready' AND d.deleted_at IS NULL "
            "AND d.superseded_by IS NULL AND s.kind = 'file' AND s.status != 'deleted' "
            "ORDER BY d.source_id, d.added_at"
        ),
        {"mime": WORKBOOK_MIME},
    )
    candidates = [(uuid.UUID(str(source)), uuid.UUID(str(document))) for source, document in rows]
    if not candidates:
        return []
    # One pass over the decisions store, whatever its size, rather than one
    # per workbook: nothing indexes a payload field.
    decided = {
        str(document): occurred_at
        for document, occurred_at in await session.execute(
            text(
                "SELECT payload->>'document_id', max(occurred_at) FROM audit_decisions "
                "WHERE kind IN (:loaded, :failed) GROUP BY 1"
            ),
            {"loaded": WORKBOOK_TABLES_LOADED, "failed": WORKBOOK_TABLES_FAILED},
        )
    }
    lost = {
        str(source): occurred_at
        for source, occurred_at in await session.execute(
            text(
                "SELECT payload->>'source_id', max(occurred_at) FROM audit_decisions "
                "WHERE kind = :lost GROUP BY 1"
            ),
            {"lost": SANDBOX_DATABASE_LOST},
        )
    }
    eligible: list[tuple[uuid.UUID, uuid.UUID]] = []
    for source_id, document_id in candidates:
        at = decided.get(str(document_id))
        since = lost.get(str(source_id))
        if at is None or (since is not None and at < since):
            eligible.append((source_id, document_id))
    return eligible


async def backfill_workbook_tables(
    factory: async_sessionmaker[AsyncSession], settings: Settings
) -> int:
    """Load the tables of every workbook indexed before its sheets became
    tables. `M11-FIX-ING-230`, issue #850. Called at worker start, after
    `forget_lost_databases` and `sweep_workbook_tables`.

    A sheet's tables load only when its workbook is ingested
    (`M11-FIX-ING-224`), so without this a workbook added before `0.9.12`
    has none until someone happens to re-index, and nothing tells them to.
    Only the tables load — its passages and embeddings are left alone. Each
    load records a decision, which is what stops the next start doing it
    again, so the work is bounded by the number of workbooks and happens
    once.

    Raises when the sandbox instance cannot be reached, checked before every
    workbook: `load_workbook_tables` would record that as the workbook's
    failure, and a sandbox that is merely not up yet is a reason to wait for
    the next start, not a fact about the file. A workbook whose file cannot
    be read right now is skipped the same way, recording nothing. So is one
    deleted after the scan.
    Returns how many workbooks were loaded.
    """
    admin_url = settings.sandbox_database_url.get_secret_value()
    async with session_scope(factory) as session:
        pending = await _workbooks_without_tables(session)
    loaded = 0
    touched: set[uuid.UUID] = set()
    try:
        for source_id, document_id in pending:
            await asyncio.to_thread(sandbox.known_databases, admin_url)
            async with session_scope(factory) as session:
                live = (
                    await session.execute(
                        text(
                            "SELECT path FROM documents WHERE id = :id AND deleted_at IS NULL "
                            "AND superseded_by IS NULL AND status = 'ready'"
                        ),
                        {"id": document_id},
                    )
                ).first()
            if live is None:
                continue
            if not await asyncio.to_thread(Path(paths.to_container(str(live[0]))).is_file):
                # Not readable from here now — a folder outside the mount, a
                # drive not plugged in. Like a sandbox not up yet, that is a
                # reason to try at the next start, not the workbook's failure.
                log.info(
                    "workbook_backfill_deferred",
                    source_id=str(source_id),
                    document_id=str(document_id),
                    reason="file not readable",
                )
                continue
            outcome = await load_workbook_tables(factory, settings, source_id, document_id)
            log.info(
                "workbook_tables_backfilled",
                source_id=str(source_id),
                document_id=str(document_id),
                tables=len(outcome.tables),
                failure=outcome.failure,
            )
            loaded += 1
            touched.add(source_id)
    finally:
        # Nothing is indexing, so nothing else refreshes the folder: a load that
        # failed puts it in attention now, as `reload_source` does — including
        # the folders loaded before the sandbox went away mid-way.
        from askwell import ingest

        for source_id in touched:
            async with session_scope(factory) as session:
                await ingest.refresh_source(
                    session, source_id, settings.ocr_confidence_threshold, settings
                )
    return loaded
