"""Load an inferred CSV/spreadsheet table into its own sandbox database.
`M4-CSV-ING-094`.

`docs/data-sources.md` §2 and `askwell.table_infer`'s own docstring: parsing
and inference (`M4-CSV-ING-092`/`M4-CSV-ING-093`) never apply a guess
silently. This module is the next step — turning a reviewed inference into a
real, queryable table — and inherits the same rule: a column `table_infer`
could not resolve with confidence (`ColumnInference.ambiguous`, which
includes an undecided date format) is loaded as `text`, verbatim, rather than
coerced into the type Askwell merely suspects. Answering the clarification
that resolves it is what makes `reload_source` below re-load that one column
as the real type — the table is queryable from the first load, just narrower
than it will be once every question is answered.

**Isolation is `askwell.sandbox`, the same as a dump's (C3).** A CSV's own
content is never executed as SQL the way a dump's is — every value is cast in
Python and inserted through a parameterised statement, and every identifier
(table and column names) is generated by `askwell.sandbox`'s isolation-owning
code, never taken from the file — so there is no equivalent of "a hostile
CSV" at the level `M4-DUMP-SEC-091` tests for a dump. The sandbox is still
the right home for the data: it is one database per source, with no route to
Askwell's own database or the network, which is exactly the property a wrong
guess about someone's numbers should not be able to spread past.

**Row failures are reported, never dropped.** `docs/backlog`'s own validation
rule for this ticket. A value that cannot be cast to its column's type — an
`abc` in an integer column no inference flagged as ambiguous, because the
sample that decided the type did not happen to include it — is skipped, and
its 1-indexed row number (counting the header as row 1, the same convention
`table_infer.MalformedTable` uses) is collected onto `LoadResult.failed_rows`
rather than aborting the load or silently omitting the row with no trace.

**A CSV's owner role is unsealed and resealed around a reload, not sealed for
good.** `askwell.dump_import.import_dump` calls `sandbox.seal_owner` the
moment a dump succeeds because a dump is never touched again (`docs/backlog`:
"an import is a single attempt"). A table source is different: answering a
date-format clarification later needs a further owner-privileged write, so
`load_source` seals the same way a dump does when it finishes, and
`reload_source` brackets its own rebuild with `sandbox.unseal_owner` /
`sandbox.seal_owner` rather than leaving the grant open between reloads that
may be arbitrarily far apart.

**A reload rebuilds the whole table from the source file, not one column in
place.** The alternative — `ALTER TABLE ... ALTER COLUMN ... TYPE date USING
...` — aborts the entire statement on the first row that fails to parse,
which is exactly the all-or-nothing behaviour the row-level reporting rule
exists to avoid, and doing it column-by-column would need a stable per-row
join key this table has no other reason to carry. Re-parsing the file and
re-inserting every row is more I/O for a rare, user-initiated event, in
exchange for reusing the exact same per-row cast-and-report path the initial
load already uses — one implementation of "insert a row, catch what fails",
not two.
"""

import asyncio
import re
import time
import uuid
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

import psycopg
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from askwell import audit, sandbox
from askwell.audit import Store
from askwell.config import Settings
from askwell.db.engine import session_scope
from askwell.logging import get_logger
from askwell.memory import write_schema_note
from askwell.table_infer import (
    ColumnInference,
    DateFormatVerdict,
    HeaderVerdict,
    TableInference,
    infer_csv,
    infer_xlsx,
    raise_table_inference,
)

log = get_logger(__name__)

TABLE_LOAD_STARTED = "table_load_started"
TABLE_LOAD_SUCCEEDED = "table_load_succeeded"
TABLE_LOAD_FAILED = "table_load_failed"
TABLE_COLUMN_RELOADED = "table_column_reloaded"

# Same booleans `table_infer._classify` recognises, duplicated rather than
# imported: this is the fixed vocabulary the *cast* step agrees with, and
# importing a name prefixed `_` across modules would read as a private
# implementation detail this module happens to reach into, when it is really
# a shared, stable convention both sides need to agree on independently.
_TRUE_VALUES = frozenset({"true", "t", "yes", "y", "1"})
_FALSE_VALUES = frozenset({"false", "f", "no", "n", "0"})

_NUMERIC_DATE = re.compile(r"^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})$")
_ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

_SQL_TYPE_BY_INFERRED_TYPE = {
    "integer": "bigint",
    "decimal": "numeric",
    "boolean": "boolean",
    "date": "date",
    "string": "text",
}

# Same reasoning as `dump_import.CAP_POLL_SECONDS`: a database-size query on
# every row would make the cap itself the slow part of the load, so the real
# size is polled on a cadence and the elapsed-time check, which is free,
# runs every row.
SIZE_POLL_EVERY_ROWS = 200


class TableLoadFailed(RuntimeError):
    """The table did not load. `str(exc)` is the reason — shown to the user
    and recorded as the sandbox database's drop reason, same shape as
    `dump_import.DumpImportFailed`."""


class TableCapExceeded(TableLoadFailed):
    """The load was aborted for crossing the size or time cap shared with a
    dump import (`docs/backlog` M4-CSV-ING-094's own edge case: "subject to
    the same size and time caps as a dump"). Deliberately the same caps,
    read through `askwell.dump_import`'s own settings, rather than a second
    pair of numbers a user would have to discover and set twice."""

    def __init__(self, cap: str, limit: float, message: str) -> None:
        super().__init__(message)
        self.cap = cap
        self.limit = limit


class EmptyTable(TableLoadFailed):
    """The file had nothing to load — `docs/backlog`'s own edge case: "An
    empty file — refused with the reason." Never reaches the sandbox at
    all: there is no database to create for a table with no columns."""


@dataclass(frozen=True, slots=True)
class RowFailure:
    row_number: int
    reason: str


@dataclass(frozen=True, slots=True)
class LoadResult:
    table_name: str
    sql_table_name: str
    row_count: int
    failed_rows: list[RowFailure] = field(default_factory=list)


def _format_bytes(count: float) -> str:
    value = float(count)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def _database_size(admin_url: str, database: str) -> int:
    with psycopg.connect(admin_url, autocommit=True) as admin:
        row = admin.execute("SELECT pg_database_size(%s)", (database,)).fetchone()
    assert row is not None
    return int(row[0])


# --- identifier normalisation -----------------------------------------------


def normalise_identifier(name: str, seen: set[str]) -> str:
    """A valid, unique Postgres identifier for one column or table name.

    `docs/backlog`'s own edge case: "A column name that is not a valid
    identifier — normalised, with the original recorded as a schema note so
    questions using the original name still work." `seen` makes two columns
    that normalise to the same thing (`"Amount"` and `"amount!"`) collide
    into `amount`/`amount_2` instead of one silently overwriting the other
    in the `CREATE TABLE` statement.
    """
    base = re.sub(r"[^a-z0-9_]+", "_", name.strip().lower()).strip("_") or "column"
    if base[0].isdigit():
        base = f"c_{base}"
    candidate = base
    suffix = 2
    while candidate in seen:
        candidate = f"{base}_{suffix}"
        suffix += 1
    seen.add(candidate)
    return candidate


def normalise_columns(names: list[str]) -> list[str]:
    """`normalise_identifier` applied in column order with one shared `seen`
    set — the same function `load_source` and `reload_source` both call, so
    a reload always agrees with the load it is correcting about which
    physical column a header name maps to."""
    seen: set[str] = set()
    return [normalise_identifier(name, seen) for name in names]


# --- typing and casting ------------------------------------------------------


def sql_type_for(
    column: ColumnInference, *, day_first_override: bool | None
) -> tuple[str, bool | None]:
    """The SQL type a column loads as, and the day-first/month-first
    decision a `date` column casts numeric values with — `None` when the
    column carries no such ambiguity (ISO, named-month, or not a date at
    all) or when the day-first/month-first question is not yet answered.

    An ambiguous column (`ColumnInference.ambiguous`) loads as `text`,
    verbatim, unless `day_first_override` — an answered `date_format`
    clarification's own DD/MM-vs-MM/DD verdict — resolves it. Every other
    ambiguity `table_infer` raises (a blank header, a mixed number format)
    has no discrete resolution to load against, so it stays `text` even
    after the clarification is answered; only the schema note describing it
    changes, via `askwell.reapply`.
    """
    if column.ambiguous:
        is_undecided_date = (
            column.date_format is not None
            and column.date_format.verdict is DateFormatVerdict.AMBIGUOUS
        )
        if is_undecided_date and day_first_override is not None:
            return "date", day_first_override
        return "text", None

    if column.inferred_type == "date":
        verdict = column.date_format.verdict if column.date_format is not None else None
        if verdict is DateFormatVerdict.DAY_FIRST:
            return "date", True
        if verdict is DateFormatVerdict.MONTH_FIRST:
            return "date", False
        # NOT_APPLICABLE: no numeric d/d/y value in the column at all (ISO or
        # named-month only), so no day-first/month-first decision is ever
        # consulted by `_cast_value`.
        return "date", None

    return _SQL_TYPE_BY_INFERRED_TYPE.get(column.inferred_type, "text"), None


def _parse_date(value: str, day_first: bool | None) -> Any:
    from datetime import date, datetime

    if _ISO_DATE.match(value):
        return date.fromisoformat(value)
    for fmt in ("%d %B %Y", "%d %b %Y"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            continue
    match = _NUMERIC_DATE.match(value)
    if not match:
        raise ValueError(f"{value!r} does not match a recognised date shape")
    if day_first is None:
        raise ValueError(f"{value!r} is a date whose day/month order was never decided")
    first, second, year_text = (int(part) for part in match.groups())
    year = year_text if year_text >= 100 else year_text + 2000
    day, month = (first, second) if day_first else (second, first)
    return date(year, month, day)


def cast_value(raw: str, sql_type: str, day_first: bool | None) -> Any:
    """One cell, cast to its column's SQL type — `None` for a blank cell in
    any column, never coerced to `0` or an empty string. Raises `ValueError`
    for a value that does not fit, caught per row by `_insert_rows` and
    turned into a `RowFailure` rather than aborting the load."""
    value = raw.strip()
    if not value:
        return None
    if sql_type == "bigint":
        return int(value)
    if sql_type == "numeric":
        try:
            return Decimal(value.replace(",", ""))
        except InvalidOperation as error:
            raise ValueError(f"{value!r} is not a number") from error
    if sql_type == "boolean":
        low = value.lower()
        if low in _TRUE_VALUES:
            return True
        if low in _FALSE_VALUES:
            return False
        raise ValueError(f"{value!r} is not a recognised boolean")
    if sql_type == "date":
        return _parse_date(value, day_first)
    return value


# --- creating and populating one table ---------------------------------------


def _create_table_blocking(dsn: str, sql_table_name: str, columns: list[tuple[str, str]]) -> None:
    from psycopg import sql as psql

    column_defs = psql.SQL(", ").join(
        psql.SQL("{} {}").format(psql.Identifier(name), psql.SQL(sql_type))
        for name, sql_type in columns
    )
    with psycopg.connect(dsn, autocommit=True) as conn:
        conn.execute(psql.SQL("DROP TABLE IF EXISTS {}").format(psql.Identifier(sql_table_name)))
        conn.execute(
            psql.SQL("CREATE TABLE {} ({})").format(psql.Identifier(sql_table_name), column_defs)
        )


def _insert_rows_blocking(
    dsn: str,
    admin_url: str,
    database: str,
    sql_table_name: str,
    sql_column_names: list[str],
    sql_types: list[str],
    day_firsts: list[bool | None],
    rows: list[list[str]],
    *,
    header_present: bool,
    size_cap_bytes: int,
    time_cap_seconds: float,
) -> list[RowFailure]:
    from psycopg import sql as psql

    insert_stmt = psql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        psql.Identifier(sql_table_name),
        psql.SQL(", ").join(psql.Identifier(name) for name in sql_column_names),
        psql.SQL(", ").join(psql.Placeholder() * len(sql_column_names)),
    )

    failures: list[RowFailure] = []
    start = time.monotonic()
    with psycopg.connect(dsn, autocommit=True) as conn:
        for offset, row in enumerate(rows):
            row_number = offset + (2 if header_present else 1)

            elapsed = time.monotonic() - start
            if elapsed > time_cap_seconds:
                raise TableCapExceeded(
                    "time",
                    time_cap_seconds,
                    f"Load aborted: running for {elapsed:.1f}s, over the time cap of "
                    f"{time_cap_seconds:.1f}s.",
                )
            if offset and offset % SIZE_POLL_EVERY_ROWS == 0:
                try:
                    loaded = _database_size(admin_url, database)
                except Exception:  # pragma: no cover - the database always exists here
                    loaded = None
                if loaded is not None and loaded > size_cap_bytes:
                    raise TableCapExceeded(
                        "size",
                        size_cap_bytes,
                        f"Load aborted: loaded data reached {_format_bytes(loaded)}, over "
                        f"the size cap of {_format_bytes(size_cap_bytes)}.",
                    )

            try:
                values = [
                    cast_value(row[index], sql_types[index], day_firsts[index])
                    if index < len(row)
                    else None
                    for index in range(len(sql_column_names))
                ]
                conn.execute(insert_stmt, values)
            except (ValueError, psycopg.Error) as error:
                failures.append(RowFailure(row_number, str(error)))
    return failures


# --- registering and orchestrating one source --------------------------------


async def create_table_source(session: AsyncSession, name: str, file_path: str) -> uuid.UUID:
    """Register a table source ahead of parsing and loading it — the `csv`
    counterpart of `dump_import.create_dump_source`. `root_path` carries the
    file's own path, the same column and the same reasoning: it is not a
    folder Askwell indexes in place, but it is still where this source's
    material actually is.
    """
    result = await session.execute(
        text(
            "INSERT INTO sources (kind, name, root_path, status) "
            "VALUES ('csv', :name, :root_path, 'queued') RETURNING id"
        ),
        {"name": name, "root_path": file_path},
    )
    source_id = result.scalar_one()
    await audit.record(
        session,
        Store.DECISIONS,
        "source_added",
        {"source_id": str(source_id), "name": name, "kind": "csv"},
    )
    log.info("table_source_added", source_id=str(source_id), name=name)
    return uuid.UUID(str(source_id))


def _parse_file(file_path: Path) -> list[TableInference]:
    raw = file_path.read_bytes()
    extension = file_path.suffix.lower().lstrip(".")
    if extension == "xlsx":
        return infer_xlsx(file_path.name, raw)
    return [infer_csv(file_path.name, raw)]


async def _date_format_overrides(
    session: AsyncSession, source_id: uuid.UUID
) -> dict[tuple[str, str], bool]:
    """Every answered `date_format` clarification for this source, as a
    `(table_name, column_name) -> day_first` map — the cumulative, durable
    record of every DD/MM-vs-MM/DD question answered so far, re-derived from
    `clarifications` itself rather than a second store: the clarification
    row already is the fact, and re-deriving it here is what lets
    `reload_source` rebuild correctly no matter how many separate answers
    led to this point.
    """
    rows = await session.execute(
        text(
            "SELECT subject, answer, options FROM clarifications "
            "WHERE source_id = :source_id AND status = 'answered' "
            "AND evidence->>'trigger' = 'date_format'"
        ),
        {"source_id": source_id},
    )
    overrides: dict[tuple[str, str], bool] = {}
    for subject, answer, options in rows:
        if not answer or ":" not in subject:
            continue
        table_name, column_name = (part.strip() for part in subject.split(":", 1))
        day_first_option = (options or [None])[0]
        overrides[(table_name, column_name)] = answer == day_first_option
    return overrides


async def _load_inferences(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    inferences: list[TableInference],
    *,
    overrides: dict[tuple[str, str], bool],
    is_reload: bool,
) -> list[LoadResult]:
    from askwell.dump_import import get_dump_size_cap_bytes, get_dump_time_cap_seconds

    non_empty = [inference for inference in inferences if inference.columns]
    if not non_empty:
        raise EmptyTable("the file has no rows or columns to load")

    admin_url = settings.sandbox_database_url.get_secret_value()
    owner_password = settings.sandbox_owner_password.get_secret_value()

    async with session_scope(factory) as session:
        size_cap_bytes = await get_dump_size_cap_bytes(session)
        time_cap_seconds = await get_dump_time_cap_seconds(session)
        row = (
            await session.execute(
                text("SELECT sandbox_db FROM sources WHERE id = :id"), {"id": source_id}
            )
        ).first()
        assert row is not None, "load_source called against a source that does not exist"
        database = row[0]
        if database is None:
            database = sandbox.generate_name()
            await sandbox.create_database(session, admin_url, database)
            await session.execute(
                text("UPDATE sources SET sandbox_db = :db, status = 'indexing' WHERE id = :id"),
                {"db": database, "id": source_id},
            )
        elif is_reload:
            await sandbox.unseal_owner(session, admin_url, database)
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_LOAD_STARTED,
            {"source_id": str(source_id), "database": database, "reload": is_reload},
        )

    dsn = sandbox.owner_url(admin_url, database, owner_password)
    results: list[LoadResult] = []
    # Shared across every sheet in this source, not reset per inference — two
    # sheets whose names normalise the same way (`"Data"` and `"DATA!"`) must
    # not both claim the identifier `data`, the same collision
    # `normalise_columns` already guards against within one table's columns.
    sql_table_names: set[str] = set()

    try:
        for inference in non_empty:
            sql_table_name = normalise_identifier(inference.table_name, sql_table_names)
            sql_column_names = normalise_columns([column.name for column in inference.columns])

            sql_types: list[str] = []
            day_firsts: list[bool | None] = []
            for column in inference.columns:
                override = overrides.get((inference.table_name, column.name))
                sql_type, day_first = sql_type_for(column, day_first_override=override)
                sql_types.append(sql_type)
                day_firsts.append(day_first)

            await asyncio.to_thread(
                _create_table_blocking,
                dsn,
                sql_table_name,
                list(zip(sql_column_names, sql_types, strict=True)),
            )
            failures = await asyncio.to_thread(
                _insert_rows_blocking,
                dsn,
                admin_url,
                database,
                sql_table_name,
                sql_column_names,
                sql_types,
                day_firsts,
                inference.rows,
                header_present=inference.header.verdict is HeaderVerdict.PRESENT,
                size_cap_bytes=size_cap_bytes,
                time_cap_seconds=time_cap_seconds,
            )
            results.append(
                LoadResult(
                    table_name=inference.table_name,
                    sql_table_name=sql_table_name,
                    row_count=len(inference.rows) - len(failures),
                    failed_rows=failures,
                )
            )
    except Exception as error:
        reason = (
            str(error) if isinstance(error, TableLoadFailed) else f"{type(error).__name__}: {error}"
        )
        payload: dict[str, object] = {
            "source_id": str(source_id),
            "database": database,
            "reason": reason,
        }
        if isinstance(error, TableCapExceeded):
            payload["cap"] = error.cap
        async with session_scope(factory) as session:
            if not is_reload:
                await sandbox.drop_database(session, admin_url, database, reason=reason)
                await session.execute(
                    text(
                        "UPDATE sources SET sandbox_db = NULL, status = 'attention', "
                        "last_error = :error WHERE id = :id"
                    ),
                    {"error": reason, "id": source_id},
                )
            else:
                await session.execute(
                    text(
                        "UPDATE sources SET status = 'attention', last_error = :error "
                        "WHERE id = :id"
                    ),
                    {"error": reason, "id": source_id},
                )
            await audit.record(session, Store.DECISIONS, TABLE_LOAD_FAILED, payload)
        log.warning("table_load_failed", source_id=str(source_id), database=database, reason=reason)
        if isinstance(error, TableLoadFailed):
            raise
        raise TableLoadFailed(reason) from error

    async with session_scope(factory) as session:
        await sandbox.seal_owner(session, admin_url, database)
        if not is_reload:
            # Written once, at the load that first creates the table —
            # `write_schema_note`'s own supersession rule only retires a
            # prior note for a `user`-origin write, so calling this again on
            # every reload would accumulate a duplicate `inferred` note per
            # reload rather than replacing the one already there. A reload
            # changes row counts, not the table's existence or its column
            # names, so nothing here goes stale across one.
            for inference, result in zip(non_empty, results, strict=True):
                await write_schema_note(
                    session,
                    source_id=source_id,
                    table_name=inference.table_name,
                    column_name=None,
                    description=(
                        f"Loaded as table `{result.sql_table_name}`, "
                        f"{result.row_count} row(s), {len(inference.columns)} column(s)."
                        + (
                            f" {len(result.failed_rows)} row(s) failed to load."
                            if result.failed_rows
                            else ""
                        )
                    ),
                    origin="inferred",
                    confidence=1.0,
                )
                sql_names = normalise_columns([c.name for c in inference.columns])
                for sql_name, column in zip(sql_names, inference.columns, strict=True):
                    if sql_name != column.name:
                        await write_schema_note(
                            session,
                            source_id=source_id,
                            table_name=inference.table_name,
                            column_name=column.name,
                            description=(
                                f"Loaded as column `{sql_name}` — the original header "
                                f"was {column.name!r}, which is not a valid column name."
                            ),
                            origin="inferred",
                            confidence=1.0,
                        )
        await session.execute(
            text("UPDATE sources SET status = 'ready', last_indexed_at = now() WHERE id = :id"),
            {"id": source_id},
        )
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_LOAD_SUCCEEDED,
            {
                "source_id": str(source_id),
                "database": database,
                "tables": [result.sql_table_name for result in results],
                "rows": sum(result.row_count for result in results),
                "failed_rows": sum(len(result.failed_rows) for result in results),
            },
        )
    log.info(
        "table_load_succeeded",
        source_id=str(source_id),
        database=database,
        tables=len(results),
        failed_rows=sum(len(result.failed_rows) for result in results),
    )
    return results


async def process_table_source(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    file_path: str,
) -> list[LoadResult]:
    """Parse, raise clarifications, and load — the one entry point a worker
    job calls end to end for a newly added CSV or spreadsheet source.

    Parsing and clarification-raising (`M4-CSV-ING-092`/`093`,
    `askwell.table_infer`) run first and unconditionally: every column lands
    in `schema_notes` and every unresolved one becomes a real clarification
    regardless of what the load itself does, the same as before this ticket
    existed. Loading (this ticket) always follows in the same run — a column
    still ambiguous when it does simply loads as `text`, per `sql_type_for`.
    """
    inferences = _parse_file(Path(file_path))

    async with session_scope(factory) as session:
        for inference in inferences:
            await raise_table_inference(session, source_id, inference)

    return await _load_inferences(
        factory, settings, source_id, inferences, overrides={}, is_reload=False
    )


async def load_source(
    factory: async_sessionmaker[AsyncSession],
    settings: Settings,
    source_id: uuid.UUID,
    file_path: str,
) -> list[LoadResult]:
    """Load already-inferred, already-raised tables — split out from
    `process_table_source` so a test (or a future retry path) can load
    without re-raising clarifications a source already has."""
    inferences = _parse_file(Path(file_path))
    return await _load_inferences(
        factory, settings, source_id, inferences, overrides={}, is_reload=False
    )


async def reload_source(
    factory: async_sessionmaker[AsyncSession], settings: Settings, source_id: uuid.UUID
) -> list[LoadResult] | None:
    """Re-load every table this source produced, applying every
    `date_format` clarification answered so far. `askwell.reapply` calls
    this once a date-format clarification's own answer is recorded, so a
    column loaded as `text` because its day/month order was undecided
    becomes a real `date` the moment that is settled.

    Returns `None` without touching the sandbox when the source is not a
    `csv` source, or has not loaded yet — `askwell.reapply`'s dependency
    resolution matches on `schema_notes` alone and cannot tell a table
    source's inferred note from any other source's, so this is the one place
    that actually checks.
    """
    async with session_scope(factory) as session:
        row = (
            await session.execute(
                text("SELECT kind, root_path, sandbox_db FROM sources WHERE id = :id"),
                {"id": source_id},
            )
        ).first()
        if row is None or row[0] != "csv" or row[2] is None:
            return None
        root_path = row[1]
        overrides = await _date_format_overrides(session, source_id)

    inferences = _parse_file(Path(root_path))
    results = await _load_inferences(
        factory, settings, source_id, inferences, overrides=overrides, is_reload=True
    )
    async with session_scope(factory) as session:
        await audit.record(
            session,
            Store.DECISIONS,
            TABLE_COLUMN_RELOADED,
            {
                "source_id": str(source_id),
                "tables": [result.sql_table_name for result in results],
                "failed_rows": sum(len(result.failed_rows) for result in results),
            },
        )
    return results
